package com.msd.fundari.utils.telegram;

public enum BotState {
  LANGUAGE_SELECT,
  IDLE,
  PROJECT_TYPE,

  // business application states
  BUSINESS_PROJECT_NAME,
  BUSINESS_INDUSTRY,
  BUSINESS_BUSINESS_AGE,
  BUSINESS_AVG_MONTHLY_PROFIT,
  BUSINESS_NET_PROFIT,
  BUSINESS_ESTIMATE_VALUE_OF_ASSETS,
  BUSINESS_TEAM_SIZE,
  BUSINESS_HAS_ASSETS,
  BUSINESS_HAS_DEBTS_OR_LOANS,
  BUSINESS_REGION_OF_ACTIVITY
}
