package com.msd.fundari.utils.telegram;

public enum BotState {
  LANGUAGE_SELECT,
  IDLE,
  PROJECT_TYPE,

  // business application states
  BUSINESS_PROJECT_NAME,
  BUSINESS_INDUSTRY,
  BUSINESS_BUSINESS_AGE,
  BUSINESS_AVG_MONTHLY_PROFIT,
  BUSINESS_NET_PROFIT,
  BUSINESS_ESTIMATE_VALUE_OF_ASSETS,
  BUSINESS_TEAM_SIZE,
  BUSINESS_HAS_ASSETS,
  BUSINESS_HAS_DEBTS_OR_LOANS,
  BUSINESS_REGION_OF_ACTIVITY,

  // startup application states
  START_UP_PROJECT_NAME,

  START_UP_STAGE,
  START_UP_DESC,
  START_UP_HAS_LAST_MONTH_PROFIT,
  START_UP_LAST_MONTH_PROFIT,
  START_UP_ACTIVE_USERS,
  START_UP_INVESTMENT,
  START_UP_TEAM_SIZE,
  START_UP_COMPETITION_INFO,
  START_UP_REGION_OF_ACTIVITY,


  // idea application states
  IDEA_PROJECT_NAME
}
