spring.application.name=fundari
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.batch_size = 20
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Tashkent
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.batch_fetch_style=dynamic

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}
server.forward-headers-strategy=native


server.servlet.session.timeout=300m
server.servlet.session.persistent=true

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

upload.url=${URL}

# Mapping for serving uploaded files
spring.resources.static-locations=file:${upload.directory}

jwt.secret_key=${JWT_SECRET_KEY}

server.port=${PORT}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.com.msd.food_bot=error
logging.level.root=error


spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true


spring.jpa.open-in-view=false

spring.ai.openai.api-key=${AI_TOKEN}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama3-70b-8192

telegram.bot.secret=${BOT_SECRET}
telegram.bot.enabled=true
telegram.bot.webhook-url=${BOT_URI}
telegram.bot.webhook-path=${BOT_PATH}
telegram.bot.username=${BOT_USERNAME}
telegram.bot.token=${BOT_TOKEN}

logging.level.org.telegram=DEBUG


